"""Conversation handler states — replaces the unnamed range(31)."""

from enum import IntEnum, auto


class State(IntEnum):
    CHOOSING = 0
    CONVERSATION = auto()
    CONVERSATION_HISTORY = auto()
    TASKS_MENU = auto()
    TASKS_ADD_PROMPT = auto()
    TASKS_ADD_DAYS = auto()
    TASKS_ADD_TIME = auto()
    TASKS_ADD_INTERVAL = auto()
    TASKS_CONFIRM_PLAN = auto()
    SETTINGS_MENU = auto()
    MODELS_MENU = auto()
    STORAGE_MENU = auto()
    API_KEY_INPUT = auto()
    PERSONA_MENU = auto()
    PERSONA_INPUT = auto()
    REMINDERS_MENU = auto()
    REMINDERS_INPUT = auto()
    KNOWLEDGE_MENU = auto()
    KNOWLEDGE_INPUT = auto()
    SEARCH_INPUT = auto()
    SHORTCUTS_MENU = auto()
    SHORTCUTS_INPUT = auto()
    TAGS_INPUT = auto()
    PINNED_CONTEXT_INPUT = auto()
    TEMPLATES_MENU = auto()
    BOOKMARKS_MENU = auto()
    PROMPT_LIBRARY = auto()
    PROMPT_ADD = auto()
    BRIEFING_MENU = auto()
    URL_MONITOR_MENU = auto()
    URL_MONITOR_INPUT = auto()
    MODEL_SEARCH_INPUT = auto()


# Backward-compatible aliases — handlers can import directly
CHOOSING = State.CHOOSING
CONVERSATION = State.CONVERSATION
CONVERSATION_HISTORY = State.CONVERSATION_HISTORY
TASKS_MENU = State.TASKS_MENU
TASKS_ADD_PROMPT = State.TASKS_ADD_PROMPT
TASKS_ADD_DAYS = State.TASKS_ADD_DAYS
TASKS_ADD_TIME = State.TASKS_ADD_TIME
TASKS_ADD_INTERVAL = State.TASKS_ADD_INTERVAL
TASKS_CONFIRM_PLAN = State.TASKS_CONFIRM_PLAN
SETTINGS_MENU = State.SETTINGS_MENU
MODELS_MENU = State.MODELS_MENU
STORAGE_MENU = State.STORAGE_MENU
API_KEY_INPUT = State.API_KEY_INPUT
PERSONA_MENU = State.PERSONA_MENU
PERSONA_INPUT = State.PERSONA_INPUT
REMINDERS_MENU = State.REMINDERS_MENU
REMINDERS_INPUT = State.REMINDERS_INPUT
KNOWLEDGE_MENU = State.KNOWLEDGE_MENU
KNOWLEDGE_INPUT = State.KNOWLEDGE_INPUT
SEARCH_INPUT = State.SEARCH_INPUT
SHORTCUTS_MENU = State.SHORTCUTS_MENU
SHORTCUTS_INPUT = State.SHORTCUTS_INPUT
TAGS_INPUT = State.TAGS_INPUT
PINNED_CONTEXT_INPUT = State.PINNED_CONTEXT_INPUT
TEMPLATES_MENU = State.TEMPLATES_MENU
BOOKMARKS_MENU = State.BOOKMARKS_MENU
PROMPT_LIBRARY = State.PROMPT_LIBRARY
PROMPT_ADD = State.PROMPT_ADD
BRIEFING_MENU = State.BRIEFING_MENU
URL_MONITOR_MENU = State.URL_MONITOR_MENU
URL_MONITOR_INPUT = State.URL_MONITOR_INPUT
MODEL_SEARCH_INPUT = State.MODEL_SEARCH_INPUT
